delete from blockstoworkers;
delete from companies;
delete from infoblocks;
delete from possibleanswers;
delete from questions;
delete from workersanswers;
delete from workers;
delete from workersstates;
delete from codes;
delete from lastcodestate;
alter sequence companies_id_seq restart;
alter sequence infoblocks_id_seq restart;
alter sequence possibleanswers_id_seq restart;
alter sequence questions_id_seq restart;
alter sequence workers_id_seq restart;
